
spring:
  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
